version: '3.8'

services:
  ximple-library-db:
    container_name: ximple-library-db
    image: postgres:bullseye
    volumes:
      - ximple-library-db:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: always
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 4s
      timeout: 2s
      retries: 5

  back:
    container_name: ximple-library-back
    image: ximple-library-back
    build: ./app
    volumes:
      - ./app:/app
    restart: unless-stopped
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      ximple-library-db:
        condition: service_healthy

volumes:
  ximple-library-db:
